RD /S /Q "%~dp0Release"
MD "%~dp0Release"
MD "%~dp0Release\lib"
MD "%~dp0Release\lib\x86"
MD "%~dp0Release\lib\x64"
MD "%~dp0Release\lib\x86\Release"
MD "%~dp0Release\lib\x86\Debug"
MD "%~dp0Release\lib\x64\Release"
MD "%~dp0Release\lib\x64\Debug"
MKLINK /D  /J "%~dp0Release\include" "%~dp0Source\NTAssassin\include"
MKLINK "%~dp0Release\lib\x64\Debug\NTAssassin.lib" "%~dp0Source\x64\Debug\NTAssassin.lib"
MKLINK "%~dp0Release\lib\x64\Debug\NTAssassin.pdb" "%~dp0Source\NTAssassin\x64\Debug\NTAssassin.pdb"
MKLINK "%~dp0Release\lib\x64\Release\NTAssassin.lib" "%~dp0Source\x64\Release\NTAssassin.lib"
MKLINK "%~dp0Release\lib\x64\Release\NTAssassin.pdb" "%~dp0Source\NTAssassin\x64\Release\NTAssassin.pdb"
MKLINK "%~dp0Release\lib\x86\Debug\NTAssassin.lib" "%~dp0Source\Win32\Debug\NTAssassin.lib"
MKLINK "%~dp0Release\lib\x86\Debug\NTAssassin.pdb" "%~dp0Source\NTAssassin\Win32\Debug\NTAssassin.pdb"
MKLINK  "%~dp0Release\lib\x86\Release\NTAssassin.lib" "%~dp0Source\Win32\Release\NTAssassin.lib"
MKLINK "%~dp0Release\lib\x86\Release\NTAssassin.pdb" "%~dp0Source\NTAssassin\Win32\Release\NTAssassin.pdb"
MKLINK /D  /J "%~dp0Release\NAC" "%~dp0Source\NAC\bin\Release\net5.0\publish"
PAUSE