RD /S /Q "%~dp0Release"
MD "%~dp0Release"
MD "%~dp0Release\lib"
MD "%~dp0Release\lib\x86"
MD "%~dp0Release\lib\x64"
MD "%~dp0Release\lib\x86\Release"
MD "%~dp0Release\lib\x86\Debug"
MD "%~dp0Release\lib\x64\Release"
MD "%~dp0Release\lib\x64\Debug"
XCOPY /E /I /H /R /K /Y "%~dp0Source\NTAssassin\include" "%~dp0Release\include"
COPY /Y "%~dp0Source\x64\Debug\NTAssassin.lib" "%~dp0Release\lib\x64\Debug\NTAssassin.lib"
COPY /Y "%~dp0Source\x64\Debug\NTAssassin.pdb" "%~dp0Release\lib\x64\Debug\NTAssassin.pdb"
COPY /Y "%~dp0Source\x64\Release\NTAssassin.lib" "%~dp0Release\lib\x64\Release\NTAssassin.lib"
COPY /Y "%~dp0Source\Win32\Debug\NTAssassin.lib" "%~dp0Release\lib\x86\Debug\NTAssassin.lib"
COPY /Y "%~dp0Source\Win32\Debug\NTAssassin.pdb" "%~dp0Release\lib\x86\Debug\NTAssassin.pdb"
COPY /Y "%~dp0Source\Win32\Release\NTAssassin.lib" "%~dp0Release\lib\x86\Release\NTAssassin.lib"
PAUSE