// This file generated by NTAssassin Auxiliary Compiler V1.0.0.0
// Do not modify manually

#pragma once

#include "include\NTAssassin\NTAssassin.h"

EXTERN_C BYTE SYM_Hijack_LoadProcAddr_InjectThread_x86[982];
EXTERN_C BYTE SYM_Hijack_LoadProcAddr_InjectThread_x64[1120];
EXTERN_C BYTE SYM_Hijack_CallProc_InjectThread_x86[138];
EXTERN_C BYTE SYM_Hijack_CallProc_InjectThread_x64[266];
