//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Precomp4C
//     KNSoft(knsoft.org) - Precomp4C V1.0.0.1
//     https://github.com/KNSoft/Precomp4C
//     Do not change this file manually
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

extern unsigned char SYM_Hijack_LoadProcAddr_InjectThread_x86[982];
extern unsigned char SYM_Hijack_LoadProcAddr_InjectThread_x64[1120];
extern unsigned char SYM_Hijack_CallProc_InjectThread_x86[138];
extern unsigned char SYM_Hijack_CallProc_InjectThread_x64[274];
